import Head from 'next/head'
import Avatar from '../components/Avatar'
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid"
import Image from 'next/image'
import google_logo from '../public/images/google_logo.png'
import { SearchIcon } from '@heroicons/react/outline'
import Footer from '../components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/router'



export default function Home() {
  const router = useRouter()
  const searchInputRef = useRef(null)

  const search = (e) => {
    e.preventDefault()

    const term = searchInputRef.current.value
    if (!term) return

    router.push(`/search?term=${term}`)

  }

  return (
    <div className="flex flex-col items-center h-screen">
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">

        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>

          {/* icon */}
          <ViewGridIcon className="h-10 w-10 cursor-pointer p-2 rounded-full hover:bg-gray-100" />
          <Avatar url="https://freesvg.org/img/abstract-user-flat-1.png" style={{ width: '100%', height: '100%' }} />
        </div>
      </header>

      {/* body */}
      <form className="flex flex-col items-center mt-44 flex-1 w-4/5">

        <Image src={google_logo} height={100} width={300} alt="google_logo" />

        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl xl:max-w-2xl">
          <SearchIcon className="h-5 text-gray-500 mr-3" />
          <input type="text" ref={searchInputRef} className="flex-1 focus:outline-none" />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col justify-center items-center w-1/2 space-y-2 mt-6 sm:flex-row sm:space-y-0 sm:space-x-4">
          <button onClick={search} className="button hover:ring-1  focus:outline-none active:ring-gray-300 hover:shadow-md">Google Search</button>
          <button onClick={search} className="button hover:ring-1  focus:outline-none active:ring-gray-300 hover:shadow-md">I am feeling Lucky</button>
        </div>
      </form>

      <Footer />

    </div>
  )
}
